// AUTO-GENERATED by tools/gen_bootrom.py -- do not edit.
//
// The S1 serial boot loader. Sends 'T', receives a 4-byte
// little-endian length then that many bytes into main memory
// at 0x20000000, sends 'G' and jumps there.
//
// Assembled with the same instruction encoders the processor
// is verified against (dv/core_iss/rv32e.py), so an encoding
// mistake here would already have shown up as a
// co-simulation disagreement.
//
// 35 instructions of a 128-word budget.

module bootrom (
    input  wire [8:2]  addr,   // word address, 128 words
    output reg  [31:0] rdata
);

    always @(*) begin
        case (addr)
            7'd0  : rdata = 32'h300000B7;
            7'd1  : rdata = 32'h20000337;
            7'd2  : rdata = 32'h40000537;
            7'd3  : rdata = 32'h05400113;
            7'd4  : rdata = 32'h00208023;
            7'd5  : rdata = 32'h00000213;
            7'd6  : rdata = 32'h00000393;
            7'd7  : rdata = 32'h0580046F;
            7'd8  : rdata = 32'h007292B3;
            7'd9  : rdata = 32'h00526233;
            7'd10 : rdata = 32'h00838393;
            7'd11 : rdata = 32'h02000113;
            7'd12 : rdata = 32'hFE2396E3;
            7'd13 : rdata = 32'h00000493;
            7'd14 : rdata = 32'h00448C63;
            7'd15 : rdata = 32'h0380046F;
            7'd16 : rdata = 32'h00950133;
            7'd17 : rdata = 32'h00510023;
            7'd18 : rdata = 32'h00148493;
            7'd19 : rdata = 32'hFEDFF06F;
            7'd20 : rdata = 32'h0040A183;
            7'd21 : rdata = 32'h0011F193;
            7'd22 : rdata = 32'hFE019CE3;
            7'd23 : rdata = 32'h04700113;
            7'd24 : rdata = 32'h00208023;
            7'd25 : rdata = 32'h0040A183;
            7'd26 : rdata = 32'h0011F193;
            7'd27 : rdata = 32'hFE019CE3;
            7'd28 : rdata = 32'h00030067;
            7'd29 : rdata = 32'h0040A183;
            7'd30 : rdata = 32'h0021F193;
            7'd31 : rdata = 32'hFE018CE3;
            7'd32 : rdata = 32'h0000A283;
            7'd33 : rdata = 32'h0FF2F293;
            7'd34 : rdata = 32'h00040067;
            // Everything above the program reads as zero,
            // which decodes as an illegal instruction and
            // traps -- better than running into whatever
            // happens to be there.
            default: rdata = 32'h00000000;
        endcase
    end

endmodule
