// AUTO-GENERATED by tools/gen_padring.py -- do not edit.
//
// The chip as it is manufactured: soc_top surrounded by a ring of
// IO pad cells. This is the module that gets hardened, and the one
// whose frequency, area and power figures are the chip's real
// numbers -- P0's core-only harden was never comparable to them.
//
// 39 signal pads and 8 supply pads, 47 in total.
//
// The placer positions these by instance name, and the same names
// appear in pd/designs/tinytrust_soc/pins.mk. Both come out of the
// generator, so they cannot drift apart.

module soc_chip (
    inout  wire        pad_clk,
    inout  wire        pad_rst_n,
    inout  wire        pad_uart_rx,
    inout  wire        pad_uart_tx,
    inout  wire        pad_alert,
    inout  wire [1:0]  pad_strap,
    inout  wire [15:0] pad_gpio_in,
    inout  wire [15:0] pad_gpio_out
);

    wire clk_i, rst_n_i, uart_rx_i, uart_tx_o, sec_alert_o;
    wire [1:0] straps_i;
    wire [15:0] gpio_in_i;
    wire [15:0] gpio_out_o;

    // ---- signal pads ----
    sg13g2_IOPadIn      sg13g2_IOPad_clk (.pad(pad_clk), .p2c(clk_i));
    sg13g2_IOPadIn      sg13g2_IOPad_rst_n (.pad(pad_rst_n), .p2c(rst_n_i));
    sg13g2_IOPadIn      sg13g2_IOPad_uart_rx (.pad(pad_uart_rx), .p2c(uart_rx_i));
    sg13g2_IOPadOut4mA  sg13g2_IOPad_uart_tx (.pad(pad_uart_tx), .c2p(uart_tx_o));
    sg13g2_IOPadOut4mA  sg13g2_IOPad_alert (.pad(pad_alert), .c2p(sec_alert_o));
    sg13g2_IOPadIn      sg13g2_IOPad_strap_0 (.pad(pad_strap[0]), .p2c(straps_i[0]));
    sg13g2_IOPadIn      sg13g2_IOPad_strap_1 (.pad(pad_strap[1]), .p2c(straps_i[1]));
    sg13g2_IOPadIn      sg13g2_IOPad_gpio_in_0 (.pad(pad_gpio_in[0]), .p2c(gpio_in_i[0]));
    sg13g2_IOPadIn      sg13g2_IOPad_gpio_in_1 (.pad(pad_gpio_in[1]), .p2c(gpio_in_i[1]));
    sg13g2_IOPadIn      sg13g2_IOPad_gpio_in_2 (.pad(pad_gpio_in[2]), .p2c(gpio_in_i[2]));
    sg13g2_IOPadIn      sg13g2_IOPad_gpio_in_3 (.pad(pad_gpio_in[3]), .p2c(gpio_in_i[3]));
    sg13g2_IOPadIn      sg13g2_IOPad_gpio_in_4 (.pad(pad_gpio_in[4]), .p2c(gpio_in_i[4]));
    sg13g2_IOPadIn      sg13g2_IOPad_gpio_in_5 (.pad(pad_gpio_in[5]), .p2c(gpio_in_i[5]));
    sg13g2_IOPadIn      sg13g2_IOPad_gpio_in_6 (.pad(pad_gpio_in[6]), .p2c(gpio_in_i[6]));
    sg13g2_IOPadIn      sg13g2_IOPad_gpio_in_7 (.pad(pad_gpio_in[7]), .p2c(gpio_in_i[7]));
    sg13g2_IOPadIn      sg13g2_IOPad_gpio_in_8 (.pad(pad_gpio_in[8]), .p2c(gpio_in_i[8]));
    sg13g2_IOPadIn      sg13g2_IOPad_gpio_in_9 (.pad(pad_gpio_in[9]), .p2c(gpio_in_i[9]));
    sg13g2_IOPadIn      sg13g2_IOPad_gpio_in_10 (.pad(pad_gpio_in[10]), .p2c(gpio_in_i[10]));
    sg13g2_IOPadIn      sg13g2_IOPad_gpio_in_11 (.pad(pad_gpio_in[11]), .p2c(gpio_in_i[11]));
    sg13g2_IOPadIn      sg13g2_IOPad_gpio_in_12 (.pad(pad_gpio_in[12]), .p2c(gpio_in_i[12]));
    sg13g2_IOPadIn      sg13g2_IOPad_gpio_in_13 (.pad(pad_gpio_in[13]), .p2c(gpio_in_i[13]));
    sg13g2_IOPadIn      sg13g2_IOPad_gpio_in_14 (.pad(pad_gpio_in[14]), .p2c(gpio_in_i[14]));
    sg13g2_IOPadIn      sg13g2_IOPad_gpio_in_15 (.pad(pad_gpio_in[15]), .p2c(gpio_in_i[15]));
    sg13g2_IOPadOut4mA  sg13g2_IOPad_gpio_out_0 (.pad(pad_gpio_out[0]), .c2p(gpio_out_o[0]));
    sg13g2_IOPadOut4mA  sg13g2_IOPad_gpio_out_1 (.pad(pad_gpio_out[1]), .c2p(gpio_out_o[1]));
    sg13g2_IOPadOut4mA  sg13g2_IOPad_gpio_out_2 (.pad(pad_gpio_out[2]), .c2p(gpio_out_o[2]));
    sg13g2_IOPadOut4mA  sg13g2_IOPad_gpio_out_3 (.pad(pad_gpio_out[3]), .c2p(gpio_out_o[3]));
    sg13g2_IOPadOut4mA  sg13g2_IOPad_gpio_out_4 (.pad(pad_gpio_out[4]), .c2p(gpio_out_o[4]));
    sg13g2_IOPadOut4mA  sg13g2_IOPad_gpio_out_5 (.pad(pad_gpio_out[5]), .c2p(gpio_out_o[5]));
    sg13g2_IOPadOut4mA  sg13g2_IOPad_gpio_out_6 (.pad(pad_gpio_out[6]), .c2p(gpio_out_o[6]));
    sg13g2_IOPadOut4mA  sg13g2_IOPad_gpio_out_7 (.pad(pad_gpio_out[7]), .c2p(gpio_out_o[7]));
    sg13g2_IOPadOut4mA  sg13g2_IOPad_gpio_out_8 (.pad(pad_gpio_out[8]), .c2p(gpio_out_o[8]));
    sg13g2_IOPadOut4mA  sg13g2_IOPad_gpio_out_9 (.pad(pad_gpio_out[9]), .c2p(gpio_out_o[9]));
    sg13g2_IOPadOut4mA  sg13g2_IOPad_gpio_out_10 (.pad(pad_gpio_out[10]), .c2p(gpio_out_o[10]));
    sg13g2_IOPadOut4mA  sg13g2_IOPad_gpio_out_11 (.pad(pad_gpio_out[11]), .c2p(gpio_out_o[11]));
    sg13g2_IOPadOut4mA  sg13g2_IOPad_gpio_out_12 (.pad(pad_gpio_out[12]), .c2p(gpio_out_o[12]));
    sg13g2_IOPadOut4mA  sg13g2_IOPad_gpio_out_13 (.pad(pad_gpio_out[13]), .c2p(gpio_out_o[13]));
    sg13g2_IOPadOut4mA  sg13g2_IOPad_gpio_out_14 (.pad(pad_gpio_out[14]), .c2p(gpio_out_o[14]));
    sg13g2_IOPadOut4mA  sg13g2_IOPad_gpio_out_15 (.pad(pad_gpio_out[15]), .c2p(gpio_out_o[15]));

    // ---- supply pads ----
    // (* keep *) is load-bearing here. A supply pad has no ports and
    // drives nothing, so nothing in the netlist refers to it and synthesis
    // removes it as dead logic. The failure then surfaces much later and
    // somewhere else, when the pad placer goes looking for it by name:
    //
    //   [ERROR PAD-0102] Unable to find instance: ..._vdd1
    (* keep *) sg13g2_IOPadVdd      sg13g2_IOPad_vdd0 ();
    (* keep *) sg13g2_IOPadVss      sg13g2_IOPad_vss0 ();
    (* keep *) sg13g2_IOPadIOVdd    sg13g2_IOPad_iovdd0 ();
    (* keep *) sg13g2_IOPadIOVss    sg13g2_IOPad_iovss0 ();
    (* keep *) sg13g2_IOPadVdd      sg13g2_IOPad_vdd1 ();
    (* keep *) sg13g2_IOPadVss      sg13g2_IOPad_vss1 ();
    (* keep *) sg13g2_IOPadIOVdd    sg13g2_IOPad_iovdd1 ();
    (* keep *) sg13g2_IOPadIOVss    sg13g2_IOPad_iovss1 ();

    // ---- the chip ----
    soc_top #(.USE_MACRO(1), .N_RAM_MACRO(4), .GPIO_W(16)) u_soc (
        .clk(clk_i), .rst_n(rst_n_i),
        .uart_rx(uart_rx_i), .uart_tx(uart_tx_o),
        .gpio_out(gpio_out_o), .gpio_in(gpio_in_i),
        .sec_alert(sec_alert_o), .straps(straps_i)
    );

endmodule
