#!/usr/bin/env python3
"""Generate the chip top level and its pad lists (S1-C).

Writes:
    rtl/soc/soc_chip.v      soc_top wrapped in a ring of IO pad cells
    pd/designs/tinytrust_soc/pins.mk   the IO_*_PINS lists for the flow

WHY GENERATE IT
The placer positions pads by *instance name*, so every name in the Verilog has
to appear in the matching side list in the flow config, spelled identically.
There are 47 of them. Typing that twice by hand and keeping the two in step is
exactly the sort of thing that produces an afternoon of confusing placement
errors, so both come out of this file instead.

PIN BUDGET
The chip really needs 15 signals: clock, reset, serial in and out, the alert
pin and two mode straps. A 64-pin package has far more room than that, so the
general-purpose I/O is widened to 16 in and 16 out to use it. Those pins cost
almost nothing -- the port is already a parameter -- and every one of them is
somewhere firmware can show what it is doing during bring-up, which is the
thing you cannot add after manufacture.

    python tools/gen_padring.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

GPIO_W = 16

# Each entry: (instance suffix, kind, chip port, internal signal)
#   in   -> sg13g2_IOPadIn        pad -> p2c
#   out  -> sg13g2_IOPadOut4mA    c2p -> pad
def signal_pads():
    p = []
    p.append(("clk",      "in",  "pad_clk",      "clk_i"))
    p.append(("rst_n",    "in",  "pad_rst_n",    "rst_n_i"))
    p.append(("uart_rx",  "in",  "pad_uart_rx",  "uart_rx_i"))
    p.append(("uart_tx",  "out", "pad_uart_tx",  "uart_tx_o"))
    p.append(("alert",    "out", "pad_alert",    "sec_alert_o"))
    for i in range(2):
        p.append(("strap_%d" % i, "in", "pad_strap[%d]" % i, "straps_i[%d]" % i))
    for i in range(GPIO_W):
        p.append(("gpio_in_%d" % i, "in", "pad_gpio_in[%d]" % i,
                  "gpio_in_i[%d]" % i))
    for i in range(GPIO_W):
        p.append(("gpio_out_%d" % i, "out", "pad_gpio_out[%d]" % i,
                  "gpio_out_o[%d]" % i))
    return p


# Two of each supply, so the ring has power coming in from opposite sides
# rather than everything hanging off one corner.
POWER_PADS = [
    ("vdd0",   "sg13g2_IOPadVdd"),
    ("vss0",   "sg13g2_IOPadVss"),
    ("iovdd0", "sg13g2_IOPadIOVdd"),
    ("iovss0", "sg13g2_IOPadIOVss"),
    ("vdd1",   "sg13g2_IOPadVdd"),
    ("vss1",   "sg13g2_IOPadVss"),
    ("iovdd1", "sg13g2_IOPadIOVdd"),
    ("iovss1", "sg13g2_IOPadIOVss"),
]

PREFIX = "sg13g2_IOPad_"
PWR_PREFIX = "sg13g2_IOPad_"


def inst_name(suffix):
    return PREFIX + suffix


def main():
    sigs = signal_pads()
    all_insts = [inst_name(s[0]) for s in sigs] + \
                [PWR_PREFIX + n for n, _ in POWER_PADS]

    # ---- distribute round the four sides ----
    # Clock and reset go on the south edge together, away from the noisy
    # switching outputs on the north.
    south = [inst_name(x) for x in
             ["clk", "rst_n", "uart_rx", "uart_tx", "alert", "strap_0", "strap_1"]]
    south += [PWR_PREFIX + "vdd0", PWR_PREFIX + "vss0"]
    south += [inst_name("gpio_in_%d" % i) for i in range(0, 3)]

    west = [inst_name("gpio_in_%d" % i) for i in range(3, 12)]
    west += [PWR_PREFIX + "iovdd0", PWR_PREFIX + "iovss0"]

    north = [inst_name("gpio_in_%d" % i) for i in range(12, 16)]
    north += [inst_name("gpio_out_%d" % i) for i in range(0, 7)]
    north += [PWR_PREFIX + "vdd1", PWR_PREFIX + "vss1"]

    east = [inst_name("gpio_out_%d" % i) for i in range(7, 16)]
    east += [PWR_PREFIX + "iovdd1", PWR_PREFIX + "iovss1"]

    placed = south + west + north + east
    assert sorted(placed) == sorted(all_insts), "a pad is placed twice or not at all"

    # ---- the chip top level ----
    out_v = os.path.join(ROOT, "rtl", "soc", "soc_chip.v")
    with open(out_v, "w", newline="\n") as f:
        f.write("// AUTO-GENERATED by tools/gen_padring.py -- do not edit.\n")
        f.write("//\n")
        f.write("// The chip as it is manufactured: soc_top surrounded by a ring of\n")
        f.write("// IO pad cells. This is the module that gets hardened, and the one\n")
        f.write("// whose frequency, area and power figures are the chip's real\n")
        f.write("// numbers -- P0's core-only harden was never comparable to them.\n")
        f.write("//\n")
        f.write("// %d signal pads and %d supply pads, %d in total.\n"
                % (len(sigs), len(POWER_PADS), len(placed)))
        f.write("//\n")
        f.write("// The placer positions these by instance name, and the same names\n")
        f.write("// appear in pd/designs/tinytrust_soc/pins.mk. Both come out of the\n")
        f.write("// generator, so they cannot drift apart.\n")
        f.write("\n")
        f.write("module soc_chip (\n")
        f.write("    inout  wire        pad_clk,\n")
        f.write("    inout  wire        pad_rst_n,\n")
        f.write("    inout  wire        pad_uart_rx,\n")
        f.write("    inout  wire        pad_uart_tx,\n")
        f.write("    inout  wire        pad_alert,\n")
        f.write("    inout  wire [1:0]  pad_strap,\n")
        f.write("    inout  wire [%d:0] pad_gpio_in,\n" % (GPIO_W - 1))
        f.write("    inout  wire [%d:0] pad_gpio_out\n" % (GPIO_W - 1))
        f.write(");\n\n")

        f.write("    wire clk_i, rst_n_i, uart_rx_i, uart_tx_o, sec_alert_o;\n")
        f.write("    wire [1:0] straps_i;\n")
        f.write("    wire [%d:0] gpio_in_i;\n" % (GPIO_W - 1))
        f.write("    wire [%d:0] gpio_out_o;\n\n" % (GPIO_W - 1))

        f.write("    // ---- signal pads ----\n")
        for suffix, kind, port, sig in sigs:
            name = inst_name(suffix)
            if kind == "in":
                f.write("    sg13g2_IOPadIn      %s (.pad(%s), .p2c(%s));\n"
                        % (name, port, sig))
            else:
                f.write("    sg13g2_IOPadOut4mA  %s (.pad(%s), .c2p(%s));\n"
                        % (name, port, sig))

        f.write("\n    // ---- supply pads ----\n")
        f.write("    // (* keep *) is load-bearing here. A supply pad has no ports and\n")
        f.write("    // drives nothing, so nothing in the netlist refers to it and synthesis\n")
        f.write("    // removes it as dead logic. The failure then surfaces much later and\n")
        f.write("    // somewhere else, when the pad placer goes looking for it by name:\n")
        f.write("    //\n")
        f.write("    //   [ERROR PAD-0102] Unable to find instance: ..._vdd1\n")
        for n, cell in POWER_PADS:
            f.write("    (* keep *) %-20s %s ();\n" % (cell, PWR_PREFIX + n))
        f.write("\n    // ---- the chip ----\n")
        f.write("    soc_top #(.USE_MACRO(1), .N_RAM_MACRO(4), .GPIO_W(%d)) u_soc (\n"
                % GPIO_W)
        f.write("        .clk(clk_i), .rst_n(rst_n_i),\n")
        f.write("        .uart_rx(uart_rx_i), .uart_tx(uart_tx_o),\n")
        f.write("        .gpio_out(gpio_out_o), .gpio_in(gpio_in_i),\n")
        f.write("        .sec_alert(sec_alert_o), .straps(straps_i)\n")
        f.write("    );\n\n")
        f.write("endmodule\n")

    # ---- the pad lists for the flow ----
    out_mk = os.path.join(ROOT, "pd", "designs", "tinytrust_soc", "pins.mk")
    os.makedirs(os.path.dirname(out_mk), exist_ok=True)
    with open(out_mk, "w", newline="\n") as f:
        f.write("# AUTO-GENERATED by tools/gen_padring.py -- do not edit.\n")
        f.write("# Instance names must match rtl/soc/soc_chip.v exactly; both\n")
        f.write("# come out of the generator so they cannot drift apart.\n\n")
        for side, lst in (("NORTH", north), ("EAST", east),
                          ("SOUTH", south), ("WEST", west)):
            f.write("export IO_%s_PINS = %s\n" % (side, " \\\n".join(lst)))
            f.write("\n")

    print("wrote %s" % out_v)
    print("wrote %s" % out_mk)
    print("  %d signal pads, %d supply pads, %d total"
          % (len(sigs), len(POWER_PADS), len(placed)))
    print("  north %d  east %d  south %d  west %d"
          % (len(north), len(east), len(south), len(west)))


if __name__ == "__main__":
    main()
