#!/usr/bin/env python3
"""Generate rom/bootrom_stub.v — a 128 x 32-bit synthesized mask ROM with
deterministic pseudorandom contents.

Purpose: area calibration only. Real boot ROM contents (assembled from
rom/bootrom.S) will replace the stub via this same generator once the ROM
code exists; pseudorandom data gives a realistic (slightly pessimistic) area
figure because synthesis can't minimize structured constants away.
"""
import pathlib

WORDS = 128  # 512 bytes


def xorshift32(x: int) -> int:
    x ^= (x << 13) & 0xFFFFFFFF
    x ^= x >> 17
    x ^= (x << 5) & 0xFFFFFFFF
    return x & 0xFFFFFFFF


def main() -> None:
    words = []
    x = 0x7A5A5A51  # fixed seed: deterministic output
    for _ in range(WORDS):
        x = xorshift32(x)
        words.append(x)

    out = pathlib.Path(__file__).resolve().parent.parent / "rom" / "bootrom_stub.v"
    with out.open("w", newline="\n") as f:
        f.write(
            "// AUTO-GENERATED by tools/gen_bootrom_stub.py — do not edit.\n"
            "// 512 B mask ROM, pseudorandom placeholder contents (calibration).\n\n"
            "module bootrom (\n"
            "    input  wire [8:2]  addr,   // word address, 128 words\n"
            "    output reg  [31:0] rdata\n"
            ");\n\n"
            "    always @(*) begin\n"
            "        case (addr)\n"
        )
        for i, w in enumerate(words):
            f.write(f"            7'd{i}: rdata = 32'h{w:08X};\n")
        f.write(
            "            default: rdata = 32'h00000000;\n"
            "        endcase\n"
            "    end\n\n"
            "endmodule\n"
        )
    print(f"wrote {out} ({WORDS} words)")


if __name__ == "__main__":
    main()
