# AUTO-GENERATED by tools/gen_padring.py -- do not edit.
# Instance names must match rtl/soc/soc_chip.v exactly; both
# come out of the generator so they cannot drift apart.

export IO_NORTH_PINS = sg13g2_IOPad_gpio_in_12 \
sg13g2_IOPad_gpio_in_13 \
sg13g2_IOPad_gpio_in_14 \
sg13g2_IOPad_gpio_in_15 \
sg13g2_IOPad_gpio_out_0 \
sg13g2_IOPad_gpio_out_1 \
sg13g2_IOPad_gpio_out_2 \
sg13g2_IOPad_gpio_out_3 \
sg13g2_IOPad_gpio_out_4 \
sg13g2_IOPad_gpio_out_5 \
sg13g2_IOPad_gpio_out_6 \
sg13g2_IOPad_vdd1 \
sg13g2_IOPad_vss1

export IO_EAST_PINS = sg13g2_IOPad_gpio_out_7 \
sg13g2_IOPad_gpio_out_8 \
sg13g2_IOPad_gpio_out_9 \
sg13g2_IOPad_gpio_out_10 \
sg13g2_IOPad_gpio_out_11 \
sg13g2_IOPad_gpio_out_12 \
sg13g2_IOPad_gpio_out_13 \
sg13g2_IOPad_gpio_out_14 \
sg13g2_IOPad_gpio_out_15 \
sg13g2_IOPad_iovdd1 \
sg13g2_IOPad_iovss1

export IO_SOUTH_PINS = sg13g2_IOPad_clk \
sg13g2_IOPad_rst_n \
sg13g2_IOPad_uart_rx \
sg13g2_IOPad_uart_tx \
sg13g2_IOPad_alert \
sg13g2_IOPad_strap_0 \
sg13g2_IOPad_strap_1 \
sg13g2_IOPad_vdd0 \
sg13g2_IOPad_vss0 \
sg13g2_IOPad_gpio_in_0 \
sg13g2_IOPad_gpio_in_1 \
sg13g2_IOPad_gpio_in_2

export IO_WEST_PINS = sg13g2_IOPad_gpio_in_3 \
sg13g2_IOPad_gpio_in_4 \
sg13g2_IOPad_gpio_in_5 \
sg13g2_IOPad_gpio_in_6 \
sg13g2_IOPad_gpio_in_7 \
sg13g2_IOPad_gpio_in_8 \
sg13g2_IOPad_gpio_in_9 \
sg13g2_IOPad_gpio_in_10 \
sg13g2_IOPad_gpio_in_11 \
sg13g2_IOPad_iovdd0 \
sg13g2_IOPad_iovss0

